# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='date',
        ),
    ]
