# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180528_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
